version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install dependencies needed for running tests
      # - npm install

      # Upgrade AWS CLI to the latest version
      - pip3 install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      # - npm test
  post_build:
    commands:
      - rm -rf api/dist
      - mkdir api/dist api/dist/client
      - rm -rf api/node_modules client/node_modules

      # Client
      - cd client
      # - rm -r node_modules
      - npm install
      - npm run build
      - mv build/* ../api/dist/client
      - cd ..

      # Remove existing node_modules to clear dev dependencies
      - cd api
      # - rm -r node_modules
      - npm install
      - npm run build
      - cp /opt/elasticbeanstalk/deployment/env .env
      - cd ..

      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml

      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  files:
    - template-export.yml
    - template-configuration.json
